# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
notifications:
  email: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports # newer cmake
    packages:
      - cmake
      - cmake-data
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ "$TRAVIS_JULIA_VERSION" == 0.6 ]]; then julia -e 'Pkg.clone(pwd()); Pkg.build("OSQP"); Pkg.test("OSQP"; coverage=true)'; else julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("OSQP"); Pkg.test("OSQP"; coverage=true)'; fi
after_success:
  - if [[ "$TRAVIS_JULIA_VERSION" == 0.6 ]]; then julia -e 'cd(Pkg.dir("OSQP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'; else julia --project -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'; fi
